# Generated by Django 4.2.6 on 2023-10-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=4, default=0, max_digits=4,
                                            verbose_name='Географическая широта местонахождения транспорта')),
                ('long', models.DecimalField(decimal_places=4, default=0, max_digits=4,
                                             verbose_name='Географическая долгота местонахождения транспорта')),
                ('radius', models.DecimalField(decimal_places=4, default=0, max_digits=4,
                                               verbose_name='Радиус круга поиска транспорта')),
                ('type',
                 models.CharField(choices=[('A', 'All'), ('C', 'Car'), ('B', 'Bike'), ('S', 'Scooter')], max_length=10,
                                  verbose_name='Тип транспорта')),
            ],
        ),
    ]
