# Generated by Django 4.2.6 on 2023-10-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canBeRented', models.BooleanField(default=False, verbose_name='Можно ли арендовать транспорт?')),
                ('transportType',
                 models.CharField(choices=[('C', 'Car'), ('B', 'Bike'), ('S', 'Scooter')], max_length=10,
                                  verbose_name='Тип транспорта')),
                ('model', models.CharField(max_length=100, verbose_name='Модель транспорта')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет транспорта')),
                ('identifier', models.CharField(max_length=20, verbose_name='Номерной знак')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('latitude', models.DecimalField(decimal_places=2, default=0, max_digits=5,
                                                 verbose_name='Географическая широта местонахождения транспорта')),
                ('longitude', models.DecimalField(decimal_places=2, default=0, max_digits=5,
                                                  verbose_name='Географическая долгота местонахождения транспорта')),
                ('minutePrice', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True,
                                                    verbose_name='Цена аренды за минуту')),
                ('dayPrice', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True,
                                                 verbose_name='Цена аренды за сутки')),
            ],
        ),
    ]
