# Generated by Django 4.2.6 on 2023-10-20 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transports',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    verbose_name='Хозяин транспорта'),
        ),
    ]
